service: mastodon-diagram

custom:
  initialUrl: "https://mastodon.social"
  responsesBucket: "billie-talk-demo-tracing"

provider:
    name: aws
    region: us-east-1
    runtime: provided
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - 's3:ListBucket'
          Resource:
              Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: ServerlessDeploymentBucket
        - Effect: 'Allow'
          Action:
              - 's3:PutObject'
          Resource:
              Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: ServerlessDeploymentBucket
                    - '/*'
        - Effect: 'Allow'
          Action:
              - 's3:PutObject'
          Resource:
              Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - "${self:custom.responsesBucket}"
                    - '/*'
    s3:
        responsesBucket:
            Ref: responseBucket

plugins:
    - ./vendor/bref/bref

functions:
    poll:
        handler: ./entrypoints/poll.php
        description: ''
        layers:
            - ${bref:layer.php-73}
        environment:
            RESPONSE_BUCKET: ${self:custom.responsesBucket}
            INITIAL_URL: ${self:custom.initialUrl}

# Exclude files from deployment
package:
    exclude:
        - 'spec/**'

resources:
  Resources:
    responseBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.responsesBucket}
