#!/usr/bin/env bash

set -euo pipefail

cleanup() {
        local pids=$(jobs -pr)
        [ -n "$pids" ] && kill $pids
}
trap "cleanup" INT QUIT TERM EXIT SIGINT SIGTERM EXIT

( cd frontend && amplify mock ) &

until curl -f "http://localhost:20005" ; do
  sleep 1
done

( cd frontend && echo ng e2e )
