#!/usr/bin/env bash

set -euo pipefail

trap "exit" INT TERM ERR
trap "kill 0" EXIT

( cd frontend && amplify mock ) &

until curl -f "http://localhost:20005" ; do
  sleep 1
done

( cd frontend && ng e2e )

wait
