#!/usr/bin/env bash

set -euo pipefail

cleanup() {
  jobs -pr | xargs kill
}
trap "cleanup" INT QUIT TERM EXIT SIGINT SIGTERM EXIT

(cd frontend && amplify mock) &

until curl -f "http://localhost:20005"; do
  sleep 1
done

(cd frontend && npm run-script e2e)
