on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    name: amplify-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          coverage: none
      - uses: actions/setup-node@v1
      - run: sudo wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O /usr/local/bin/php-cs-fixer
      - run: sudo chmod +x /usr/local/bin/php-cs-fixer
      - run: npm install -g @angular/cli
      - run: npm install -g @aws-amplify/cli
      - name: aws configure
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_DEFAULT_REGION"
      ##
      - uses: actions/checkout@v2
      ##
      - run: composer install
      - run: ( cd frontend && npm ci )
      - name: amplify init && amplify push
        run: |
          (
            cd frontend
            amplify init --yes \
                         --amplify '{ "envName": "production" }' \
                         --providers '{
                              "amplify-provider-awscloudformation": { \
                                "useProfile": true,
                                "profileName": "default"  \
                              } \
                            }'
            amplify add auth
            amplify add storage
            amplify push
          )
      - run: make lint-frontend
      - name: make test-frontend
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          make test-frontend

      - run: |
        (
          cd frontend
          export PATH=$(npm bin):$PATH
          cd ..
          make amplify-deploy
        )