on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    name: amplify-deploy
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          coverage: none
      - uses: actions/setup-node@v1
      - run: composer install
      - run: make lint-frontend
      - run: make test-frontend
      - run: make amplify-deploy