on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          coverage: none
      - uses: actions/setup-node@v1
      - uses: nanasess/setup-chromedriver@master
      - run: sudo wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O /usr/local/bin/php-cs-fixer
      - run: sudo chmod +x /usr/local/bin/php-cs-fixer
      - run: npm install -g @angular/cli
      - uses: actions/checkout@v2
      - run: composer install
      - run: ( cd frontend && npm ci )
      - run: |
          (
            cd frontend
            export PATH=$(npm bin):$PATH
            amplify push
          )
      - run: make lint
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          make test