on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          coverage: none
      - uses: actions/setup-node@v1
      - run: sudo wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O /usr/local/bin/php-cs-fixer
      - run: sudo chmod +x /usr/local/bin/php-cs-fixer
      - run: composer install
      - run: make lint
      - run: make test